import { jetbrainsMono } from "@/ts/fonts";
import type { Metadata } from "next";
import React from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className}  antialiased w-screen h-screen`}>{children}</body>
    </html>
  );
}
